apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'expo-module'

android {
  compileSdkVersion safeExtGet("compileSdkVersion", 34)
  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 24)
    targetSdkVersion safeExtGet("targetSdkVersion", 34)
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
  }
  kotlinOptions { jvmTarget = "11" }
  namespace "space.manus.shorts.detox.appdetector"
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${kotlinVersion()}"
}
