apply plugin: 'expo-module-gradle-plugin'
apply plugin: 'kotlin-kapt'

expoModule {
  canBePublished false
}

android {
  namespace "com.shortsdetox.appdetector"
}

dependencies {
  def room_version = "2.6.1"
  implementation "androidx.room:room-runtime:$room_version"
  implementation "androidx.room:room-ktx:$room_version"
  kapt "androidx.room:room-compiler:$room_version"
}
